print ('DEFAULT clans.lua')
CLAN_OF_PLAYER = {}
CLAN_OF_PLAYER[1] = 0
CLAN_OF_PLAYER[2] = 0
CLAN_OF_PLAYER[3] = 0
CLAN_OF_PLAYER[4] = 0
CLAN_OF_PLAYER[5] = 0
CLAN_OF_PLAYER[6] = 0
CLAN_OF_PLAYER[7] = 0
CLAN_OF_PLAYER[8] = 0

TOWN_TIER_SPEC = {}